-- Migration 009: AI Career Advisor
-- Phase 14 — Stores personalized career advice generated by AI providers.
BEGIN;

CREATE TABLE IF NOT EXISTS career_advice (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id        UUID NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    user_id               UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    resume_id             UUID NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    job_id                UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    provider              VARCHAR(20) NOT NULL DEFAULT 'mock',
    career_paths          JSONB NOT NULL DEFAULT '[]'::jsonb,
    skill_recommendations JSONB NOT NULL DEFAULT '[]'::jsonb,
    project_suggestions   JSONB NOT NULL DEFAULT '[]'::jsonb,
    interview_tips        JSONB NOT NULL DEFAULT '[]'::jsonb,
    salary_insights       JSONB NOT NULL DEFAULT '{}'::jsonb,
    overall_summary       TEXT NOT NULL DEFAULT '',
    confidence_score      INT NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexing for fast lookup
CREATE INDEX IF NOT EXISTS idx_career_advice_app_id ON career_advice(application_id);
CREATE INDEX IF NOT EXISTS idx_career_advice_user_id ON career_advice(user_id);
CREATE INDEX IF NOT EXISTS idx_career_advice_job_id ON career_advice(job_id);

-- Auto-update trigger
DROP TRIGGER IF EXISTS trg_career_advice_updated_at ON career_advice;
CREATE TRIGGER trg_career_advice_updated_at
    BEFORE UPDATE ON career_advice
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMIT;
